plugins:
  - rubocop-rails
  - rubocop-rspec

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/v1/equipments_spec.rb'

RSpec/ScatteredSetup:
  Exclude:
    - 'spec/requests/v1/equipments_spec.rb'

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

RSpec/VariableName:
  AllowedPatterns:
    - '\AAuthorization\z'
