name: Audit

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
      - run: bundle install
      - run: bundler-audit
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
      - run: bundle install
      - run: brakeman

